### ISSUE TITLE
How to get private links?

### ISSUE THREAD

**Issue by macchigualt** [szafranek/delicious-exporter#1]
Very nice piece of code indeed. I'm stuck as any other into exporting my thousands bookmarks from Delicious.
Your code grab just public links. How to grab the private ones as well? 
I tried to modify your code adding an authentication with my profile but I'm not so keen on coding so it didn't work...

Or conversely do you know how in Delicious massively make all my links public at once?

Any hint?

Thank you.

Greg

**Comment by aeldron** [comment]
I'm not sure how to get around the private links issue.  I can see what the code is doing, iterating through the public pages, grabbing all the links and outputting them to an HTML page.  Maybe there is a way to add a log in step so that the private links would also be visible, just like what happens in a browser window?

Unfortunately, I don't know Ruby on Rails well enough to be able to add that.  I'm planning to tweak the code a bit to make it output the same XML format Del.icio.us used in the past so that we can re-import it to a new cloud-based service (e.g. pinboard or diigo).

@szafranek I can contribute to your project and push my changes if you want.

**Comment by szafranek** [comment]
Sorry the late reply, I missed the notifications.

I didn't have private links, so didn't implement it. I'm afraid I won't be able to do it any time soon. I can give you a pointer, though: the script is using curl to scrap pages. curl allows you to login to page that uses cookies (del.icio.us is such a site). So you need to modify the script, so it:

1. logs in and saves the cookie to a file
2. uses that cookie file in the scrapping request, so curl acts as if it's logged in.

You can find out more about it [here](http://stackoverflow.com/a/12399126/1854105).

@aeldron: I haven't used Pinboard, but I'm pretty sure it accepts `bookmarks.html` format. It's format used by Chrome and Firefox. You can always just give it a try.
BTW, the script is just pure Ruby, no Rails knowledge is necessary :).

**Comment by szafranek** [comment]
I found few hours and added support for logging in and exporting all links, including private ones. Check out the [docs](https://github.com/szafranek/delicious-exporter) for details.

**Comment by aeldron** [comment]
You, sir, are a marvel!  :)

**Comment by macchigualt** [comment]
Wonderful, you code works like a charm, my bookmarks now are on safe.
Thank you very much.

Greg
