### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by alekdavis** [szafranek/delicious-exporter#2]
This does not seem to work from behind a firewall, right? Or is there a way to specify proxy settings?

**Comment by Yggdrasil** [comment]
All the remote networking in this script is done through the unix `curl` utility. Curl, like many unix programs, respects the `http_proxy` and `https_proxy` environment variables. If you set those two in your shell before you run the script it should work. Like this:

```
export http_proxy http://proxy.server.com:3128
export https_proxy=https://proxy.server.com:6443
```
Replace the 'proxy.server.com' hostname and portnumbers with your relevant values.

If you don't use the script's 'validate' feature you can suffice with just the https_proxy, since all communication with del.icio.us is done over HTTPS.

(I haven't tested any of this, since I don't have a proxy server handy)

**Comment by szafranek** [comment]
I don't want to duplicate curl's functionality in the script, so instead I will add it to the docs. Thank you @Yggdrasil!

**Comment by alekdavis** [comment]
Fair enough. As long as there is a way to do it. Thanks.
